### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [videogular/ngx-videogular#35]
https://videogular.github.io/ngx-videogular/
 please check it 。
The link to the given document is wrong

The document is videogular2, not ngx-videogular . 
in the Getting Start section  
even The installation method given is wrong.
thank you friend.

**Comment by johnjackson** [comment]
yes,the doucment link in README is wrong,it's the old one ----videogular2

**Comment by IxquitilisSaid** [comment]
Related to (possible duplication): #20 #33

**Comment by IxquitilisSaid** [comment]
Just to be sure: Y'all (@DreamSeekerKaiser @johnjackson) are referring to the Header, Hero, and `Get started now` sections links, right? 

If so, then #40 fixed them*

\* except for the ones that depend on Gitbook (https://videogular.github.io/videogular2/docs which will be done for #33) and the `Code Samples` since I forgot to create a demo repo in the org
