### ISSUE TITLE
Press playback button - set wrong playback speed

### ISSUE THREAD

**Issue by alex-kor991** [videogular/ngx-videogular#69]
I have the following playback-values array:
<vg-playback-button [playbackValues]="[1, 2, 4, 8, 16]"</vg-playback-button>

Initial playback speed is 1 - ok. But when I press playback button, the speed 4 is set - wrong.
Must be 2.
When I add "0.5" as 1-st element in array [0.5, 1, 2, 4, 8, 16] - all is ok.

### Expected Behavior
When I press on "1" - "2" is set.

### Actual Behavior
When I press on "1" - "4" is set.

### Attachments
Initial value 1 - ok
![image](https://user-images.githubusercontent.com/89029341/129594800-1f04c065-a96c-4a6f-8872-0f1e15277aae.png)

Next value 4 - not ok
![image](https://user-images.githubusercontent.com/89029341/129594581-f8968b4d-8897-4e14-9b6d-10710b6e21d4.png)

**Comment by IxquitilisSaid** [comment]
Hey! Sorry for the uber late reply but you can find the solution to your problem [here](https://videogular.github.io/ngx-videogular/docs/modules/controls/vg-playback/), it should be `<vg-playback-button vgFor="my-video" [playbackValues]="[ '1.0', '2.0', '4.0' ]"></vg-playback-button>` for example.

But since you brought it up, I'll add a handler for it just to make y'all's life easier 😄
